# Generated by Django 2.0.2 on 2018-02-14 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmessage',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
