# Generated by Django 2.0.2 on 2018-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_appmessage_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmessage',
            name='text',
            field=models.TextField(default='Text'),
        ),
    ]
